# Generated by Django 6.0.4 on 2026-05-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
    ]
