# Generated by Django 6.0.4 on 2026-05-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taxi_type',
            field=models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('business', 'Business')], default='economy', max_length=20),
        ),
    ]
