# Generated by Django 6.0.4 on 2026-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_model',
            field=models.CharField(default='Chevrolet Cobalt', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='+998901234567', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/4140/4140048.png'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
