# Generated by Django 6.0.4 on 2026-05-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_driver_car_model_driver_phone_driver_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
